version: "3"
services:
  nginx:
    image: nginx
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./Static:/var/www/static
  backend:
    build: Backend
    image: coding-days.backend
    restart: "no"
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
  db:
    image: "mariadb:10.3"
    ports:
      - "3306:3306"
    restart: "no"
    volumes:
      - ./Data/DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_czech_ci']
