version: "3"
services:
  fe:
    build: Frontend
    image: coding-days.frontend
    restart: "${RESTART}"
    ports:
      - "8050:80"
    volumes:
      - ./Frontend/nginx:/etc/nginx/conf.d
    depends_on:
      - be
  be:
    build: Backend
    image: coding-days.backend
    restart: "${RESTART}"
    volumes:
      - ./Data:/app/Data
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      SECRET: "${SECRET}"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
  db:
    image: "mariadb:10.3"
    restart: "${RESTART}"
    ports:
      - "8056:3306"
    volumes:
      - ./Data/DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_czech_ci']
  fe_227a:
    build: UserGui
    image: coding-days.user.frontend
    restart: "${RESTART}"
    ports:
      - "8051:80"
    volumes:
      - ./UserGui/nginx_227a:/etc/nginx/conf.d
    depends_on:
      - be_227a
  be_227a:
    build: UserApi
    image: coding-days.user.backend
    restart: "${RESTART}"
    environment:
      MYSQL_HOST: "${MYSQL_HOST_227a}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD_227a}"
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      DASHBOARD_ADMIN: "${DASHBOARD_ADMIN_227a}"
      DASHBOARD_SIMON: "${DASHBOARD_SIMON_227a}"
      SECRET: "${SECRET}"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db_227a
  db_227a:
    image: "mariadb:10.3"
    restart: "${RESTART}"
    ports:
      - "8057:3306"
    volumes:
      - ./Data/DB_227a:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD_227a}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_czech_ci']
  fe_ac15:
    build: UserGui
    image: coding-days.user.frontend
    restart: "${RESTART}"
    ports:
      - "8052:80"
    volumes:
      - ./UserGui/nginx_ac15:/etc/nginx/conf.d
    depends_on:
      - be_ac15
  be_ac15:
    build: UserApi
    image: coding-days.user.backend
    restart: "${RESTART}"
    environment:
      MYSQL_HOST: "${MYSQL_HOST_ac15}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD_ac15}"
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      DASHBOARD_ADMIN: "${DASHBOARD_ADMIN_ac15}"
      DASHBOARD_SIMON: "${DASHBOARD_SIMON_ac15}"
      SECRET: "${SECRET}"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db_ac15
  db_ac15:
    image: "mariadb:10.3"
    restart: "${RESTART}"
    ports:
      - "8058:3306"
    volumes:
      - ./Data/DB_ac15:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD_ac15}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_czech_ci']
