# @host = http://localhost:5000
@host = https://coding-days.samuell.ovh

###
# @name Register
POST {{host}}/api/register/register
Content-Type: application/x-www-form-urlencoded

name=Samuel&surname=Lachman&birth=1992-03-29&phone=%2B420+773+618+280&email=samlachman%40centrum.cz&level=0&languages=hodn%C4%9B&note=

###
# @name Count
GET {{host}}/api/register/count

###
# @name InsertCypher
POST {{host}}/api/hint/insertCypher
Content-Type: application/json

{
    "secret": "2gD8xs5KtGE2S",
    "cypherResult": "84443339"
}

###
# @name TryHint
POST {{host}}/api/hint/try
Content-Type: application/json
Authorization: Bearer {{LoginTeam.response.body.token}}

{
    "teamId": "15c1b27b-db31-42ac-b935-5d8b1e040e1a",
    "cypherResult": "9df7c79a3039892080e0738d3b38be8fdc4f8c7"
}

###
# @name ListTeams
GET {{host}}/api/team/get

###
# @name RegisterTeam
POST {{host}}/api/team/register
Content-Type: application/json

{
    "secret": "2gD8xs5KtGE2S",
    "id": "0b603f2d-d8af-443d-9068-1f0b156fac15",
    "password": "aaa" 
}

###
# @name LoginTeam
POST {{host}}/api/team/login
Content-Type: application/json

{
    "name": "227a",
    "password": "s2k4Ye"
}
