@host = http://localhost:8061

###
# @name GetTemp
GET {{host}}/api/WeatherForecast

###
# @name GetCorrectFilename
GET {{host}}/api/Utils/GetCorrectFilename

###
# @name Login
POST {{host}}/api/team/loginTeam
Content-Type: application/json

{
    "name": "227a",
    "password": "62KCRx"
}
