# @host = http://localhost:5226
@host = http://localhost:8063

###
# @name GetUserCount
GET {{host}}/api/statistic/getUserCount

###
# @name Register
POST {{host}}/api/session/register
Content-Type: application/json

{
    "secret": "2gD8xs5KtGE2S",
    "name": "admin",
    "email": "admin@rangerhub.org",
    "password": "mCHb8nWn95"
}

###
# @name ForgotPassword
POST {{host}}/api/session/forgotPassword
Content-Type: application/json

{
    "name": "admin"
}

###
# @name ResetPassword
POST {{host}}/api/session/resetPassword
Content-Type: application/json

{
    "name": "admin",
    "token": "67Yf4FG2ZO9ujpeiEpdNkAHMStxw0qo9",
    "newPassword": "ahoj"
}

###
# @name Login
POST {{host}}/api/session/login
Content-Type: application/json

{
    "name": "admin",
    "password": "mCHb8nWn95"
}

###
# @name Dashboard
GET {{host}}/api/private/getDashboard
Authorization: Bearer {{Login.response.body.token}}
